name: football
description: Football App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flick_video_player: ^0.9.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  loading_indicator: ^3.1.1
  lottie: ^3.1.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  shimmer: ^3.0.0
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  video_player: ^2.9.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6

  mocktail: ^1.0.4
  retrofit_generator: ^8.0.6
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/lottie/
    - assets/herb.png
    - assets/no_img.webp
flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/herb.png"
  min_sdk_android: 24
